- name: Perl packages
  hosts: localhost
  become: yes
  tasks:
    - name: Enable CRB
      ansible.builtin.command:
        cmd: dnf config-manager --set-enabled crb
    - name: Install epel-release
      ansible.builtin.dnf:
        name: epel-release
        state: latest
    - name: Upgrade all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - postgresql-server
          - postgresql
          - perl-DBD-Pg
          - httpd
          - iproute
          - cmake
          - perl
          - perl-Archive-Tar
          - perl-Archive-Zip
          - perl-Authen-SASL
          - perl-B
          - perl-CGI
          - perl-CPAN
          - perl-HTTP-Tiny
          - perl-Data-Dumper
          - perl-Digest-SHA
          - perl-Encode
          - perl-File-stat
          - perl-IO
          - perl-JSON-PP
          - perl-Module-Metadata
          - perl-Module-Build
          - perl-Module-CoreList
          - perl-Module-CoreList-tools
          - perl-Net
          - perl-POSIX
          - perl-PathTools
          - perl-Pod-Functions
          - perl-Sys-Syslog
          - perl-Time
          - perl-URI
          - perl-constant
          - perl-debugger
          - perl-doc
          - perl-libintl
          - perl-libs
          - perl-local-lib
          - perl-perlfaq
          - perl-sigtrap
          - perl-subs
          - perl-threads
          - perl-utils
          - perl-Algorithm-Diff
          - perl-App-cpanminus
          - perl-AutoLoader
          - perl-AutoSplit
          - perl-CPAN-DistnameInfo
          - perl-CPAN-Meta
          - perl-CPAN-Meta-Requirements
          - perl-Carp
          - perl-Data-OptList
          - perl-Data-Section
          - perl-Digest
          - perl-Digest-HMAC
          - perl-Encode-Detect
          - perl-Encode-Locale
          - perl-Errno
          - perl-Error
          - perl-Exporter
          - perl-Fcntl
          - perl-File-Basename
          - perl-File-Compare
          - perl-File-Copy
          - perl-File-Fetch
          - perl-File-Find
          - perl-File-HomeDir
          - perl-File-Listing
          - perl-File-Path
          - perl-File-Temp
          - perl-File-pushd
          - perl-Getopt-Long
          - perl-I18N-LangTags
          - perl-I18N-Langinfo
          - perl-IPC-Open3
          - perl-Importer
          - perl-JSON
          - perl-LWP-MediaTypes
          - perl-MIME-Base64
          - perl-MIME-Charset
          - perl-Mail-AuthenticationResults
          - perl-Mail-DKIM
          - perl-Math-BigInt-FastCalc
          - perl-Math-BigRat
          - perl-Math-Complex
          - perl-Module-CPANfile
          - perl-Module-Load
          - perl-Module-Load-Conditional
          - perl-Net-HTTP
          - perl-Net-Ping
          - perl-Pod-Checker
          - perl-Pod-Simple
          - perl-Pod-Usage
          - perl-Safe
          - perl-Scalar-List-Utils
          - perl-Search-Dict
          - perl-Time-Local
          - perl-Unicode-Collate
          - perl-Unicode-Normalize
          - perl-Unicode-LineBreak
          - perl-Unicode-UCD
          - perl-lib
          - perl-podlators
          - perl-HTML-Template-Expr
          - perl-Mojolicious
          - perl-Log-Log4perl
        state: latest
    - name: Install Perl modules from CPAN
      ansible.builtin.shell:
        cmd:
          echo yes | cpan -T
          CGI::Application CGI::Application::Plugin::Authentication
          CGI::Application::Plugin::Session CGI::Session
    - name: Use systemd
      ansible.builtin.copy:
        src: wsl.conf
        dest: /etc/wsl.conf
        owner: root
        group: root
        modules: '0644'
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 60
        reboot_msg: "Rebooting the system to apply changes"
    - name: Stop PostgreSQL Server
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
    - name: Remove if PostgreSQL database directory exists
      ansible.builtin.file:
        path: /var/lib/pgsql/data
        state: absent
    - name: Initialize a new PostgreSQL database
      ansible.builtin.command:
        cmd: sudo -u postgres initdb -D /var/lib/pgsql/data
    - name: Create public_html directory
      ansible.builtin.file:
        path: /home/vagrant/public_html
        state: directory
    - name: Create public_html/cgi-bin directory
      ansible.builtin.file:
        path: /home/vagrant/public_html/cgi-bin
        state: directory
    - name: Create public_html/www link
      ansible.builtin.file:
        src: /home/vagrant/public_html
        dest: /home/vagrant/public_html/www
        state: link
    - name: Unlink the default WWW directory
      ansible.builtin.file:
        path: /var/www
        state: absent
    - name: Link the default WWW directory to the Vagrant public_html directory
      ansible.builtin.file:
        src: /home/vagrant/public_html
        dest: /var/www
        state: link
    - name: Start and enable PostgreSQL Server
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: yes
    - name: Create a new PostgreSQL Database
      ansible.builtin.command:
        cmd: sudo -u postgres psql --file ddl/0010-create-db.sql
    - name: Create a new PostgreSQL tables
      ansible.builtin.command:
        cmd: sudo -u vagrant psql --file ddl/0020-create-tables.sql
    - name: Change EnableSendfile to off in Apache HTTPD Server configuration
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'EnableSendfile on'
        replace: 'EnableSendfile off'
    - name: Start and enable Apache HTTPD Server
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
